name: Rust
on:
  push:
    branches: ["master"]
  merge_group:
  pull_request:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      RUST_CHANNEL: nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup default ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt clippy
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.RUST_CHANNEL }}
      - name: cargo build
        run: cargo build --quiet
      - name: cargo clippy
        run: cargo clippy --quiet
      - name: cargo test
        run: cargo test -- --nocapture --quiet
      - name: cargo fmt --check
        run: cargo fmt --check
  unused_dependencies:
    runs-on: ubuntu-latest
    env:
      RUST_CHANNEL: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup default ${{ env.RUST_CHANNEL }}
      - name: install cargo-udeps
        uses: taiki-e/install-action@cargo-udeps
      - name: cargo udeps
        run: cargo udeps
